name: Agente WhatsApp GPT

on:
  workflow_dispatch:
  push:
    paths:
      - 'entrada.json'

jobs:
  responder:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 5h55 — antes do limite de 6h
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências
        run: pip install openai requests

      - name: Rodar agente
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZAPI_INSTANCE: ${{ secrets.ZAPI_INSTANCE }}
          ZAPI_TOKEN: ${{ secrets.ZAPI_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python processar.py

      - name: Auto-reiniciar workflow
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "⏳ Reiniciando próximo ciclo..."
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/whatsapp.yml/dispatches \
            -d '{"ref": "main"}'
